SELECT * FROM TabelaDepartamento;
SELECT * FROM TabelaColaboradores;
SELECT * FROM TabelaClientes;
SELECT * FROM TabelaTelefones;
SELECT * FROM TabelaEmprestimo;
SELECT * FROM TabelaPagamentos;
SELECT * FROM TabelaScoreCredito;
SELECT * FROM TabelaConta;
SELECT * FROM TabelaClienteConta;